[build]
  # Propiedades del primer bloque [build]
  functions = "netlify/functions"
  
  # Propiedades del segundo bloque [build]
  publish = "dist"  
  command = "npm run build"

[functions]
  # Indica dónde Astro/Netlify colocará las funciones de servidor (SSR)
  directory = "netlify/functions"
  # Define el entorno de ejecución para las funciones
  node_bundler = "esbuild"

[context.production.environment]
  NODE_VERSION = "20"

# -------------------------------------------------------------
# 1. CACHÉ LARGA (1 AÑO) para archivos estáticos (bot.png)
# -------------------------------------------------------------
[[headers]]
  for = "/bot.png"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

# -------------------------------------------------------------
# 2. CACHÉ LARGA (1 AÑO) para otros assets (PNG, JPG, Fuentes)
# -------------------------------------------------------------
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,svg,ico,woff,woff2,eot,ttf,otf}"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

# -------------------------------------------------------------
# 3. CACHÉ CORTA (5 MINUTOS) para archivos HTML (Permite ver cambios)
# -------------------------------------------------------------
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=300, must-revalidate"
